version: '3'

services:
  pg:
    image: postgres:10-alpine
    container_name: magellan-db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5422:5432
  pgtest:
    image: postgres:10-alpine
    container_name: magellan-db-test
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5412:5432
  redis:
    image: redis:5-alpine
    container_name: magellan-cache
    ports:
      - 6379:6379
  redistest:
    image: redis:5-alpine
    container_name: magellan-cache-test
    ports:
      - 6380:6379